name: Build and Deploy Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          build-args: |
            BUILD_COMMAND=build
          push: true
          tags: |
            ghcr.io/different-roads/${{ github.event.repository.name }}:develop
            ghcr.io/different-roads/${{ github.event.repository.name }}:develop-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set project directory variable
        run: |
          echo "PROJECT_DIR=${{ vars.WORKING_DIR }}/yml/${{ github.event.repository.name }}-dev" >> $GITHUB_ENV

      - name: Create project directory if it doesn't exist
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ env.PROJECT_DIR }}

      - name: Generate docker-compose.yml for develop
        run: |
          cat > docker-compose.yml << EOL
          services:
            ui:
              container_name: ui-dev
              image: ghcr.io/different-roads/${{ github.event.repository.name }}:develop
              cpus: 0.5
              restart: always
              mem_limit: 256MB
              pull_policy: always
              ports:
                - "6000:80"
              networks:
                - traefik-net
              labels:
                - "traefik.http.routers.ui-dev.rule=Host(\`ui-dev.differentroads.es\`)"
                - "traefik.http.services.ui-dev.loadbalancer.server.port=80"

          networks:
            traefik-net:
              external: true
          EOL

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "${{ env.PROJECT_DIR }}"
          overwrite: true

      - name: Execute docker compose up
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.PROJECT_DIR }}
            docker compose up -d
